name: XRT CI

env:  
  RELEASE: '2024.1'  
  PIPELINE: 'xrt' 
  ENV: 'prod' 

on:
  pull_request_target:
    types: [opened, edited, synchronize]

concurrency:  
  group: ${{ github.event.pull_request.head.repo.full_name }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true 
  
jobs:
  no-auth:
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout private repository      
        uses: actions/checkout@v4   
        with:      
          repository: actions-int/composite-workflows
          github-server-url: ${{ secrets.SERVER_URL }}      
          token: ${{ secrets.ACCESS_TOKEN }}      
          path: composite-workflows
          ref: main

      - name: env dump
        run: |
          printenv
          
 
